MODULE_INCLUDES += 
MODULE_LIBRARIES += 

DYNAMIC_SYSTEM_LIBRARIES +=
STATIC_SYSTEM_LIBRARIES +=

EXTERNAL_PROJECTS += Toolbox
EXTERNAL_INCLUDES_Toolbox += logger container service concurrent exception common
#EXTERNAL_LIBRARIES_<project> += 

