include local.mk

MODULE := prucore

C_FILES = $(wildcard *.c)
CPP_FILES = $(wildcard *.cpp)

PRU_C_FILES = $(wildcard *.pc)
PRU_CPP_FILES = $(wildcard *.pcpp)

PRU_STATIC_LIBRARY := libprucore.lib

#include ../../mk/top.mk
include $(MK_DIR)/top.mk
