include local.mk

MODULE := pruipc

C_FILES = $(wildcard *.c)
CPP_FILES = $(wildcard *.cpp)

PRU_C_FILES = $(wildcard *.pc)
PRU_CPP_FILES = $(wildcard *.pcpp)

PRU_STATIC_LIBRARY := libpruipc.lib
STATIC_LIBRARY := libpruipc.a

#include ../../mk/top.mk
include $(MK_DIR)/top.mk
