MODULE_INCLUDES += prucore pruipc
MODULE_LIBRARIES += 

DYNAMIC_SYSTEM_LIBRARIES +=
STATIC_SYSTEM_LIBRARIES +=

EXTERNAL_PROJECTS += Toolbox
EXTERNAL_INCLUDES_Toolbox += exception common logger util

#EXTERNAL_LIBRARIES_<project> += 

