MODULE_INCLUDES += exception concurrent logger common util 
MODULE_LIBRARIES += 

DYNAMIC_SYSTEM_LIBRARIES +=
STATIC_SYSTEM_LIBRARIES +=

#EXTERNAL_PROJECTS += <project>
#EXTERNAL_INCLUDES_<project> +=  
#EXTERNAL_LIBRARIES_<project> += 
